### PR TITLE
docs: Fixed Example MessageOptions -> PaginationItem

### PR DESCRIPTION
**Pull request by ArnavK-09**
**Please describe the changes this PR makes and why it should be merged:** Fixed typo, import that doesn't exist in beginner code example

### CODE REVIEW

**Comment by ArnavK-09** [comment]
fixing prettier

**Comment by ArnavK-09** [comment]
Squash it

**Comment by ArnavK-09** [comment]
## Can we get contributers role in discord server by docs contribution & #919

**Comment by samarmeena** [comment]
> ## Can we get contributers role in discord server by docs contribution & #919

yeah, please leave your discord username or tag me in discord @_samar_

**Comment by ArnavK-09** [comment]
> > ## Can we get contributers role in discord server by docs contribution & #919
> 
> yeah, please leave your discord username or tag me in discord @_samar_

@samarmeena 


## **@arnavk09** ~ Dope : @ArnavK-09

**Comment by arnavk09** [comment]
> > > ## Can we get contributers role in discord server by docs contribution & #919
> > 
> > yeah, please leave your discord username or tag me in discord @_samar_
> 
> @samarmeena 
> 
> 
> ## **@arnavk09** ~ Dope : @ArnavK-09 



Interesting to see we share such a similar username!

**Comment by VictoriqueMoe** [comment]
> ## Can we get contributers role in discord server by docs contribution & #919

no

**Comment by VictoriqueMoe** [comment]
> ## Can we get contributers role in discord server by docs contribution & #919

no

**Comment by ArnavK-09** [comment]
> > ## Can we get contributers role in discord server by docs contribution & #919
> 
> no

@VictoriqueMoe 

You D🔑-evil
Trollingmmeeeeee....ԅ⁠(⁠ ͒⁠ ⁠۝ ͒⁠ ⁠)⁠ᕤ

**Comment by ArnavK-09** [comment]
> > ## Can we get contributers role in discord server by docs contribution & #919
> 
> no

@VictoriqueMoe 

You D🔑-evil
Trollingmmeeeeee....ԅ⁠(⁠ ͒⁠ ⁠۝ ͒⁠ ⁠)⁠ᕤ

**Comment by ArnavK-09** [comment]
> > > > ## Can we get contributers role in discord server by docs contribution & #919
> > > 
> > > yeah, please leave your discord username or tag me in discord @_samar_
> > 
> > @samarmeena 
> > 
> > 
> > ## **@arnavk09** ~ Dope : @ArnavK-09 
> 
> 
> 
> Interesting to see we share such a similar username!

@arnavk09 


### Loll,

> Btw u r the reason I had to put extra **-** in my GitHub user name 🥰

**Pull request merged**
