### PR TITLE
fixed context description

### PR DESCRIPTION
**Pull request by Pdzly**
**Please describe the changes this PR makes and why it should be merged:**
Changed that the description of context menues comply with that
Without this fix discordX wont work for context actions
Other stuff will be broken probably from the change discord enforces now.

## Package
- discordx

Reference
https://discord.com/channels/613425648685547541/697138785317814292/1054837953752486018
https://discord.com/channels/613425648685547541/697138785317814292/1062203446087921774

### CODE REVIEW

**Comment by samarmeena** [comment]
I appreciate your concern, but there is no direct reference to description field, as for now, description is a required field in [discord documentation](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-structure)

If you have problems while running discordx, you can create a issue with sample codes. We will look into it.

**Comment by CrystiqYT** [comment]
Have you seen the new discord api update. this breaks the old code

**Comment by Pdzly** [comment]
@samarmeena IT LITERALLY doesnt work! It is broken! Its unstable package right now! Try yourself adding a context action! The error is "Description must be 1-100 chars long!" Because with the new update '' or other "falsey" values arent valid! I am stuned that when you have 0 slashcommandoptions and therefore an empty array [] that this breaks it. But its that simple. I referenced you all the stuff you need to understand why i am concerned.

**Comment by samarmeena** [comment]
> 

okay, I understand something is broken. But application command has description field required as for now. So, please share details like, what is exactly being broken and what are the API changes, if possible, please provide discord documentation GitHub PR.

**Comment by samarmeena** [comment]
> context action

is context action only broken?

**Comment by VictoriqueMoe** [comment]
I am not understanding the issue. if context menus are broken, then why are you modifying `DApplicationCommandOption`? this code is far too generic. Please supply sample code that causes this bug. as i am able to use and execute context menus just fine.

**Pull request closed without merging**
